spring.application.name=Greeting App Development
logging.level.org.springframework.security=DEBUG
logging.level.com.spring.RestAPI=DEBUG

# H2 Database Configuration (In-Memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

server.port=3030
# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT Secret Key
jwt.secret=7aUKaAYNSgYHXptuGd+988Q3Aube0BHIVn9Xgyjzw6o=
jwt.expiration=3600000

spring.security.user.name=admin
spring.security.user.password=sachin123


spring.mail.username=Sachinkumar30690@gmail.com
spring.mail.password=uwhx zjbf ckoz viud


# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
